# Generated by Django 5.2.17 on 2026-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(db_index=True, unique=True, verbose_name='記録日時')),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='温度')),
            ],
            options={
                'verbose_name': '温度記録',
                'verbose_name_plural': '温度記録',
                'db_table': 'temps',
                'ordering': ['-dt', '-id'],
            },
        ),
    ]
